language: c
sudo: required

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
  - sudo apt-get install -y gcc-multilib g++-multilib lib32ncurses5 lib32z1
os:
  - linux

script: asdf plugin-test sml https://github.com/nverno/asdf-sml.git
